# def solution(participant, completion):
    
#     while len(completion) != 0:
#         if completion[0] in participant:
#             participant.remove(completion[0])
#             completion.pop(0)
    
#     return participant[0]

def solution(participant, completion):
    dic = {}
    
    for p in participant:
        if p in dic:
            dic[p] += 1
        else:
            dic[p] = 1
            
    for c in completion:
        dic[c] -= 1
        
    for key in dic.keys():
        if dic[key] > 0:
            return key


print(solution(["leo", "kiki", "eden"], ["eden", "kiki"]))
print(solution(["marina", "josipa", "nikola", "vinko", "filipa"], ["josipa", "filipa", "marina", "nikola"]))
print(solution(["mislav", "stanko", "mislav", "ana"], ["stanko", "ana", "mislav"]))